image: node:latest

stages:
  - test
  - build

check:
  stage: test
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
    policy: push
  script:
    - npm ci
    - npm run check


build_deploy:
  stage: build
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
    policy: pull
  variables:
    FB_API_KEY: ${FB_API_KEY}
  only:
    - master
  script:
    - echo ${FB_API_KEY}
    - npm run build
    - npm install -g firebase-tools
    - firebase deploy --token "${FIREBASE_TOKEN}" -P spd-react-project